#########
# WORLD #
#########
/gate/world/geometry/setXLength 300 cm
/gate/world/geometry/setYLength 300 cm
/gate/world/geometry/setZLength 300 cm
/gate/world/setMaterial Air

#######################################
# CT scanner for small animal imaging #
# 150x200 pixels                      #
# size of pixels : 0.14*0.14*1.0 mm3  #/
# pixels are made up of silicon       #
#######################################
####################
# CTscanner system #
####################
/gate/world/daughters/name CTscanner
/gate/world/daughters/insert box
/gate/CTscanner/placement/setTranslation 0 0 -509.3805 mm
/gate/CTscanner/placement/setRotationAxis 0 1 0
/gate/CTscanner/placement/setRotationAngle 0 deg
/gate/CTscanner/geometry/setXLength 174.08 mm
/gate/CTscanner/geometry/setYLength 174.08 mm
/gate/CTscanner/geometry/setZLength 1 mm
/gate/CTscanner/setMaterial Air
/gate/CTscanner/vis/forceWireframe
/gate/CTscanner/vis/setColor white

#############           ############
# CTSCANNER #   ---->   #  MODULE  #
#############           ############
/gate/CTscanner/daughters/name module
/gate/CTscanner/daughters/insert box
/gate/module/geometry/setXLength 174.08 mm
/gate/module/geometry/setYLength 174.08 mm
/gate/module/geometry/setZLength  1. mm
/gate/module/setMaterial Silicon
/gate/module/vis/forceWireframe
/gate/module/vis/setColor white

############           #############
#  MODULE  #   ---->   # CLUSTER_0 #
############           #############
/gate/module/daughters/name cluster
/gate/module/daughters/insert box
/gate/cluster/geometry/setXLength 174.08 mm
/gate/cluster/geometry/setYLength 174.08 mm
/gate/cluster/geometry/setZLength  1. mm
/gate/cluster/setMaterial Air
/gate/cluster/vis/forceWireframe
/gate/cluster/vis/setColor white

############             #############           ###########
#  MODULE  #   ---->     # CLUSTER_0 #   ---->   # PIXEL_0 #
############             #############           ###########
/gate/cluster/daughters/name pixel
/gate/cluster/daughters/insert box
/gate/pixel/geometry/setXLength 0.34 mm
/gate/pixel/geometry/setYLength 0.34 mm
/gate/pixel/geometry/setZLength 1.0 mm
/gate/pixel/setMaterial Silicon
/gate/pixel/vis/setColor red

# REPEAT PIXEl_0
/gate/pixel/repeaters/insert cubicArray
/gate/pixel/cubicArray/setRepeatNumberX 512
/gate/pixel/cubicArray/setRepeatNumberY 512
/gate/pixel/cubicArray/setRepeatNumberZ   1
/gate/pixel/cubicArray/setRepeatVector 0.34 0.34 0.00 mm
/gate/pixel/cubicArray/autoCenter true

# ATTACH SYSTEM
/gate/systems/CTscanner/module/attach module
/gate/systems/CTscanner/cluster_0/attach cluster
/gate/systems/CTscanner/pixel_0/attach pixel

# ATTACH LAYER
/gate/pixel/attachCrystalSD
