#	P H A N T O M
/gate/world/daughters/name brain_mri
/gate/world/daughters/insert ImageNestedParametrisedVolume
/gate/brain_mri/geometry/setImage  mac/first.mhd
/gate/brain_mri/geometry/setRangeToMaterialFile  mac/attenuation_range.dat
/gate/brain_mri/placement/setRotationAxis 1 0 0
/gate/brain_mri/placement/setRotationAngle -90 deg
/gate/brain_mri/placement/setRotationAxis 0 1 0
/gate/brain_mri/placement/setRotationAngle 180 deg
#/gate/brain_mri/placement/setTranslation 0 0 0 mm
/gate/brain_mri/vis/setVisible 1
/gate/geometry/rebuild
/gate/brain_mri/attachPhantomSD

